### ISSUE TITLE
式番号

### ISSUE THREAD

**Issue by hkubo1983** [kmiya/naist-thesis-tmpl#2]
式番号で，(1.1.1)となるべきところが(1.11)と表記され，節番号の後のピリオドが落ちているものと思われます．

setting.tex
181行目を
(修正前）\thesection\arabic{equation}}

（修正後）\thesection.\arabic{equation}}

とすれば良いかと思いますので，修正頂ければ幸いです．

**Comment by kmiya** [comment]
反応が遅くなりましたが修正しました。ご指摘ありがとうございました。
