### ISSUE TITLE
bibtex を使った際の Illegal unit of measure

### ISSUE THREAD

**Issue by kaiakiy** [kmiya/naist-thesis-tmpl#3]
bibtexを使おうとすると Illegal unit of measure (pt inserted) というエラーが出ました．
中間ファイルのmthesis.bblの中に書かれる「\newblock」を解釈中に「trueem」で躓いている様子です．

https://github.com/kmiya/naist-thesis-tmpl/blob/master/tex/setting.tex#L92

```latex
 \def\newblock{\hskip .11trueem plus .33trueem minus -.07trueem}
```
を
```latex
 \def\newblock{\hskip .11em plus .33em minus -.07em}
```
に書き換えるとエラーが出なくなりました．

latexは詳しくないのですがこれが正しい対応でしょうか？

**Comment by kmiya** [comment]
`setting.tex`は基本的に個人用設定なので、手元でお好きに修正していただいて結構です。
`truemm`や`trueem`は`jsbook`スタイル向けの設定です。例えばフォントサイズを拡大したとき、`true`をつけないと、指定した長さが一緒に拡大されてしまいます。そのため最終的な余白が若干変わる可能性があります。
参照 https://oku.edu.mie-u.ac.jp/~okumura/jsclasses/
`bibtex`の代わりに`jbibtex`などを使用するとエラーが出ないかもしれません。

**Comment by kaiakiy** [comment]
ご丁寧に解説ありがとうございます．
jbibtex は texlive では pbibtex として収録されているとのことで pbibtex を使い，その後 platex したのですが， `Illegal unit of measure` と怒られた次第です．
trueem が認識されなかったのは jplain.bst との相性だったのかもしれません．
